# This is a basic workflow that will start a build with every push

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Adding API key
        uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "${ESRI_API_KEY}"
          replace: "${{ secrets.ESRI_API_KEY }}"
          include: "src/workbc/**"
          regex: true
      - name: Build for pushing static image to OpenShift registry
        id: build-static-image-os
        uses: redhat-actions/buildah-build@v2
        with:
          image: "workbc-es-maps"
          tags: test
          context: "./src"
          containerfile: "./src/Dockerfile"
          labels: |
              app: workbc-es-maps
              app.kubernetes.io/component: workbc-es-maps
              app.kubernetes.io/instance: workbc-es-maps
              app.kubernetes.io/name: nginx
              app.kubernetes.io/part-of: workbc-es-maps-app
              app.openshift.io/runtime: nginx
              app.openshift.io/runtime-version: '1.16'
          tls-verify: false
      - name: Push Static To OpenShift Image repo
        id: push-to-os-static
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-static-image-os.outputs.image }}
          tags: ${{ steps.build-static-image-os.outputs.tags }}
          registry: image-registry.apps.silver.devops.gov.bc.ca/1c4f9c-tools
          username: ${{ secrets.API_TOKEN_4 }}
          password: ${{ secrets.API_TOKEN_4 }}
